---
- name: "Download Agent Package"
  get_url:
    url: "https://{{ teamcity_agent_server_url }}:{{ teamcity_agent_server_port }}/update/buildAgent.zip"
    dest: /tmp/buildAgent.zip
    validate_certs: no
    timeout: 60
  register: _teamcity_agent_package

- name: "Install dependencies"
  yum:
    name: "{{ item }}"
    state: present
  with_items:
       - zip
       - sudo
       - unzip

- name: "Create Agent Build dir"
  file:
    path: "{{ teamcity_agent_install_dir }}"
    state: directory
    owner: "{{ teamcity_agent_user }}"
    group: "{{ teamcity_agent_group }}"
    mode: 0755

- name: "Unpack distribution"
  unarchive:
    src: "/tmp/buildAgent.zip"
    dest: "{{ teamcity_agent_install_dir }}"
    owner: "{{ teamcity_agent_user }}"
    group: "{{ teamcity_agent_group }}"
    copy: "no"
  when: _teamcity_agent_package|changed

- name: "Add TeamCity Agent service default config"
  template:
    src: "teamcity-agent.j2"
    dest: "/etc/default/teamcity-agent"
    mode: 0644

- name: Add openvpn_ekapusta init.d daemon script
  template: src=templates/init.j2 dest=/etc/init.d/teamcity-agent mode=0751

- name: "Put TeamCity Agent service file (systemd)"
  template:
    src: "teamcity-agent.service.j2"
    dest: "/lib/systemd/system/teamcity-agent.service"
    #mode: 0644
  when: "ansible_service_mgr == 'systemd'"

- name: "Save agent auth token"
  shell: "grep authorizationToken {{ teamcity_agent_install_dir }}/conf/buildAgent.properties | sed 's/authorizationToken=//g'"
  changed_when: no
  register: _teamcity_agent_token

- name: "Create conf dir"
  file:
    path: "{{ teamcity_agent_install_dir }}/conf"
    state: directory
    owner: "{{ teamcity_agent_user }}"
    group: "{{ teamcity_agent_group }}"
    mode: 0755

- name: "Add TeamCity Agent configuration"
  template:
    src: "buildAgent.properties.j2"
    dest: "{{ teamcity_agent_install_dir }}/conf/buildAgent.properties"
    owner: "{{ teamcity_agent_user }}"
    group: "{{ teamcity_agent_group }}"
    mode: 0644

- name: "Create log dir"
  file:
    path: "{{ teamcity_agent_install_dir }}/logs"
    state: directory
    owner: "{{ teamcity_agent_user }}"
    group: "{{ teamcity_agent_group }}"
    mode: 0755

- name: "Chmod for agent.sh"
  file:
    path: /opt/buildAgent/bin/agent.sh
    owner: "{{ teamcity_agent_user }}"
    group: "{{ teamcity_agent_group }}"
    mode: 0755

- name: Ensure TeamCity Agent is running
  action: service name=teamcity-agent state=started
