---
- name: Create /root/teamcity-agent
  file:
    path: /root/teamcity-agent
    state: directory
    mode: 0755
- name: Create /root/teamcity-agent/conf
  file:
    path: /root/teamcity-agent/conf
    state: directory
    mode: 0755
- name: Create /root/teamcity-agent/conf/buildAgent.properties
  template:
    src: "buildAgent.properties.j2"
    dest: /root/teamcity-agent/conf/buildAgent.properties
- name: "Put TeamCity Agent service file (systemd)"
  template:
    src: "teamcity-agent.service.j2"
    dest: "/lib/systemd/system/teamcity-agent.service"
  when: "ansible_service_mgr == 'systemd'"
- name: Ensure TeamCity Agent is running
  action: service name=teamcity-agent state=started
